config/routes.rb
Rails.application.routes.draw do
  get     'password_resets/new'
  get     'password_resets/edit'
  root    'static_pages#home'
  get     '/help'                           ,to: 'static_pages#help'
  get     '/about'                          ,to: 'static_pages#about'
  get     '/contact'                        ,to: 'static_pages#contact'
  get     '/signup'                         ,to: 'users#new'
  post    '/signup'                         ,to: 'users#create'
  get     '/login'                          ,to: 'sessions#new'
  post    '/login'                          ,to: 'sessions#create'
  delete  '/logout'                         ,to: 'sessions#destroy'
  # Need this for CRUD operations on a given user - see the CRUD table for the provided actions
  resources :users do
    # Makes it possible to have URLs such as /users/:id/following and /users/:id/followers
    # (arranges for the routes to respond to URLs containing the user id)
    member do
      # 'get' because we're showing data, so we use the GET method
      get :following, :followers
    end
  end
  resources :account_activation,  only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # 'dependent: :destroy' ensures that if a user is deleted, so are his corresponding microposts
  has_many :microposts, dependent: :destroy
  # For following users - stored in the Relationship table, and the foreign key for a given user is the 'follower_id'
  # Destroying a user should also destroy a user's relationships, hence the 'dependent: :destroy'
  has_many :active_relationships,   class_name: "Relationship",
                                    foreign_key: "follower_id",
                                    dependent: :destroy
  has_many :passive_replationships, class_name: "Relationship",
                                    foreign_key: "followed_id",
                                    dependent: :destroy
  # Leads to a powerful combination of Active Record and array-like behavior.
  # For example, we can check if the followed users collection includes another user with the include? method,
  # or find objects through the association:
  #   user.following.include?(other_user)
  #   user.following.find(other_user)
  # We can also add and delete elements just as with arrays:
  #   user.following << other_user (the shovel operator << appends to the end of an array)
  #   user.following.delete(other_user)
  # Although in many contexts we can effectively treat following as an array, Rails is smart
  # about how it handles things under the hood. For example, code like
  #   following.include?(other_user)
  # looks like it might have to pull all the followed users out of the database to apply the include? method,
  # but in fact for efficiency Rails arranges for the comparison to happen directly in the database.
  # Also, Rails allows us to override the default, in this case using the source parameter,
  # which explicitly tells Rails that the source of the following array is the set of followed ids.
  has_many :following, through: :active_relationships,    source: :followed
  # Here, we don't actually need the 'source' key, because in the case of a :followers attribute, Rails will singularize “followers” and automatically look for the foreign key follower_id in this case
  # I've left it anyway to emphasize the parallel structure with the has_many :following association
  has_many :followers, through: :passive_replationships,  source: :follower
  # Creates getter and setter methods corresponding to a user's 'remember_token' etc
  # This allows us to get and set a @remember_token instance variable
  attr_accessor :remember_token, :activation_token, :reset_token

  # Ensure that all emails are stored in lowercase
  before_save :downcase_email

  # For email activation
  before_create :create_activation_digest

  validates :name, presence: true, length: { maximum: 50 }

  # A constant, indicated in Ruby by a name starting with a capital letter
  VALID_EMAIL_REGEX = /\A(\w+)([\w+\-.]+)(\w+)(@)([a-z\d]+)([a-z\d\-\.]+)([a-z\d]+)(\.)([a-z]+)\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false } # Rails infirs that uniqueness should be true in addition to case insensitive

  # Explaining that email regex:
  # /             start of regex
  # \A            match start of string
  # \w+           at least one word character
  # [\w+\-.]+     at least one word character, plus a hyphen or dot
  # \w+           at least one word character
  # @             exactly one literal at sign
  # [a-z\d]+      at least one letter or digit
  # [a-z\d\-.]+   at least one letter, digit, hyphen, or dot
  # [a-z\d]+      at least one letter or digit
  # \.            exactly one literal dot
  # [a-z]+        at least one letter
  # \z            match end of string
  # /             end of regex
  # i             case insensitive
  #
  # Check here for regex rules: https://rubular.com

  # This method adds the following functionality:
  # - The ability to saved a hashed password_digest attribute to the database
  # - A pair of virtual attributes (password and password_confirmation), including presnce validations upon object creation and a validation requiring that they match
  # - An 'authenticate' method that returns the user when the password is correct (and 'false' otherwise)
  # The only requirement for this method to work is for the model to have an attribute called 'password_digest'
  has_secure_password
  # 'allow_nil: true' means that the password fields can be empty.
  # This both allows the update page to not require a user to enter their password,
  # and avoids a duplicate error message on the signup page of "password is missing"
  # as 'has_secure_password' already includes a seperate presence validation that specifically catches nil passwords
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

  # Returns the hash digest of the given string using the minimum cost parameter in tests and a normal (high) cost parameter in production
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random base64 token
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for user in persistent sessions (staying logged in when the window is closed)
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest
  def authenticated?(attribute, token)
    # 'send' lets us call a method with a name of our choice by "sending" a message to a given object
    # It sends whatever we pass in to that object instance and its ancestors in the class
    # hierarchy until some method reacts - 
    # meaning that it 'has the same name'.
    # So this is really just a way of calling 'digest.activate_token' or 'digest.remember_token', etc.
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Activate the user
  def activate
    update_columns(
      activated: true,
      activated_at: Time.zone.now,
      activation_digest: nil,
    )
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # For resetting a user's password
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  # Send the password reset email
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Check if a password reset request has expired - returns a boolean value
  def password_reset_expired?
    # "The password reset was sent earlier than two hours ago."
    reset_sent_at < 2.hours.ago
  end

  # For logging out a user
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Defines a feed of microposts
  def feed
    # The ? ensures that 'id' is properly escaped before being included in hte underlying SQL query, avoiding a security hole called SQL injection
    # ID here is just an integer, so there's no danger of SQL injection, but it's a good habit to always escape variables injected into SQL statements
    # We want the microposts IF the ID is that of a user that this user is following, or of himself
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  # Follows a user
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Determines if the user is following a specific user
  def following?(other_user)
    following.include?(other_user)
  end

  private

    # Converts email to lowercase
    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Restrict the filters to act only on the :edit and :update actions
  before_action :logged_in_user,  only: [:edit, :update, :index, :destroy, :following, :followers]
  before_action :correct_user,    only: [:edit, :update]
  before_action :admin_user,      only: :destroy

  def index
    # Only show activated users in the index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    # If the user exists...
    if User.exists?(params[:id])
      @user = User.find(params[:id])
      # If the user is not yet activated, return to the root and notify the user
      if @user.activated? != true
        flash[:warning] = "This account has not been activated."
        redirect_to root_url
      end
      # Else, load up the user's microposts (with pagination):
      @microposts = @user.microposts.paginate(page: params[:page])
    # Otherwise, notify the user that this account does not exist
    else
      flash[:warning] = "This account does not exist."
      redirect_to root_url
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please follow the link in your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    user_name = User.find(params[:id]).name
    User.find(params[:id]).destroy
    flash[:success] = "User #{user_name} deleted."
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private
    # Returns a version of the 'params' hash with ONLY the permitted attributes, and raises an error if the :user attribute is missing
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # Before filters - for using with the 'before_action' command 
    # to arrange for a particular method to be called before the given actions

    # Confirms a logged in user
    def logged_in_user
      unless logged_in?
        store_location # This is defined in the sessions_helper
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # For making sure that a user is only trying to edit himself
    def correct_user
      @user = User.find(params[:id])
      # In addition to the syntax in the above method, if we're only running one command we can put the 'unless' statement on a single line
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (see https://en.gravatar.com) for a given user
  def gravatar_for(user, size: 50)
    # Convert the user's email to lowercase, get rid of leading and trailing whitespace, and get the MD5 hash of it, as that's what Gravatar URL's are based on. See here: http://en.gravatar.com/site/implement/hash/
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase.strip)
    # size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    # Image tag for the Gravatar with a 'gravatar' CSS class and alt text equal to the user's name
    image_tag(gravatar_url, alt: user.name, class:"gravatar")
  end
end

app/views/users/_follow.html.erb
<!-- 'remote: true' tells Rails to use Ajax for this form, which allows web pages to send requests asynchronously to the server without leaving the page. We want this so that we don't need to essentially redirect a user back to the user page they're on when they follow/unfollow said user. -->
<%= form_for(current_user.active_relationships.build, remote: true) do |form| %>
  <div>
    <!-- Need to send the 'followed_id' to the controller -->
    <%= hidden_field_tag :followed_id, @user.id %>
  </div>
  <%= form.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:submit_url)) do |form| %>
  <!-- Make this note the togglePassword function in assets/javascripts/users.coffee -->
  <%= javascript_tag "window.togglePassword()" %> 
  <%= render 'shared/error_messages', object: form.object %>

  <%= form.label :name %>
  <%= form.text_field :name, placeholder: 'name', class: 'form-control' %>

  <%= form.label :email %>
  <%= form.email_field :email, placeholder: 'email', class: 'form-control' %>

  <%= form.label :password %>
  <div class="row">
    <div class="col-sm-11 nopadding-right">
      <%= form.password_field :password, placeholder: 'password', class: 'form-control', id: 'password_field' %>
    </div>
    <div class="col-sm-1 nopadding">
      <%= button_tag "Show", type: 'button', id: 'toggle_password', class: "btn btn-secondary" %>
    </div>
  </div>

  <%= form.submit yield(:button_text), class: "btn btn-primary btn-block" %>
<% end %>

app/views/users/_unfollow.html.erb
<!-- 'remote: true' tells Rails to use Ajax for this form, which allows web pages to send requests asynchronously to the server without leaving the page. We want this so that we don't need to essentially redirect a user back to the user page they're on when they follow/unfollow said user. -->
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
      html: { method: :delete },
      remote: true) do |form| %>
  <%= form.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure that you want to delete #{user.name}?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>

<!-- For the form -->
<% provide(:submit_url, user_url(@user)) %>
<% provide(:button_text, "Update my account") %>

<h1>Update Your Profile!</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <!-- Render the form template partial -->
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>All Users!</h1>

<!-- will_paginate works like this:
        - Inside of a user's view, it automatically looks for a @users object,
          and then displays pagination links to access other pages
        - It requires that we paginate the results explicitly using the 'paginate' method
 -->
<%= will_paginate %>

<ul class="users">
  <!--
        Rails infers that @users is a list of User objects
        When called with a collection of users, Rails automatically iterates through them
        and renders each one with the '_user.html.erb' partial by inferring the name
        of the partial from the name of the class.
  -->
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>

<!-- For the form -->
<% provide(:submit_url, signup_path) %>
<% provide(:button_text, "Make my account") %>

<h1>Sign up!</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <!-- Render the form template partial -->
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <!-- The 'gravatar_for' method lives in users_helper.rb -->
        <%= gravatar_for @user %> 
        <%= @user.name %>
      </h1>
    </section>
    <section class="follow_stats">
      <%= render 'shared/follow_stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <!-- Make sure we don't just display an empty list -->
    <% if @user.microposts.any? %>
      <h3><%= @user.name %> has <%= @user.microposts.count %> microposts</h3>
      <ol class="microposts">
        <!-- Smart enough to automatically use the microposts template partial -->
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1>
        <%= @user.name %>
      </h1>
      <span>
        <%= link_to "view my profile", @user %>
      </span>
      <span>
        <b>Microposts:</b>
        <%= @user.microposts.count %>
      </span>
    </section>
    <section class="stats">
      <%= render 'shared/follow_stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3>
      <%= @title %>
    </h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>