config/routes.rb
Rails.application.routes.draw do
  get     'password_resets/new'
  get     'password_resets/edit'
  root    'static_pages#home'
  get     '/help'                           ,to: 'static_pages#help'
  get     '/about'                          ,to: 'static_pages#about'
  get     '/contact'                        ,to: 'static_pages#contact'
  get     '/signup'                         ,to: 'users#new'
  post    '/signup'                         ,to: 'users#create'
  get     '/login'                          ,to: 'sessions#new'
  post    '/login'                          ,to: 'sessions#create'
  delete  '/logout'                         ,to: 'sessions#destroy'
  # Need this for CRUD operations on a given user - see the CRUD table for the provided actions
  resources :users do
    # Makes it possible to have URLs such as /users/:id/following and /users/:id/followers
    # (arranges for the routes to respond to URLs containing the user id)
    member do
      # 'get' because we're showing data, so we use the GET method
      get :following, :followers
    end
  end
  resources :account_activation,  only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <small class="align-middle">
      A Ruby on Rails sample application by <a href="https://www.linkedin.com/in/amendelow/">Ari Mendelow</a>
    </small>
    <% @part = 'footer' %>
    <%= render "layouts/nav", locals: { part: @part} %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app",      root_path, id: "logo" %>
    <% @part = 'header' %>
    <%= render "layouts/nav", locals: { part: @part} %>
  </div>
</header>

app/views/layouts/_nav.html.erb
<nav>
  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "Home",    root_path %></li>
    <li><%= link_to "Help",    help_path %></li>

    <% if logged_in? %>
      <li><%= link_to "Users", users_path %></li>

      <% if @part == 'header' %>
        <li class="dropdown">
          <a href='#' class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log Out", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <% end %>
      
    <% else %>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Log in", login_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9 >
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<! [endif] -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> center"><b><%= message %></b></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>